#' Glance upon your dic samples to get the penalised deviance
#'
#' This provides a one-row dataframe with information on the overall deviance,
#'   effective number of parameters (when `type` was pD) or optimism (when
#'   `type` was popt) and resulting penalised deviance
#'
#' @param x a dic object generated by rjags::dic.samples
#'
#' @return a one-row dataframe of summary information of the dic samples
#'
#' @author Sam Clifford, \email{samuel.clifford@@qut.edu.au}
#'
#' @import data.table
#' @importFrom broom glance
#' @export
glance.dic <- function(x){

    dic.table <- with(x,
                      data.table::data.table(
                          deviance = as.numeric(deviance),
                          penalty = as.numeric(penalty),
                          type = as.character(type)
                      )
    )

    dic.return <- dic.table[ , lapply(.SD, sum), .SDcols = c("deviance", "penalty") , by=type]
    dic.return[ , deviance.penalised := penalty + deviance  ]

    return(dic.return)
}
