#' @title Dimensions of MCMC objects
#'
#' @description Retrieve dimensions of an MCMC object:
#'
#'  * `n_chain(x)` the number of chains
#'  * `n_var(x)` the number of variables.
#'  * `n_iter(x)` the number of iterations
#'
#' @export
n_chain <- function(x){
    UseMethod("n_chain")
}

#' @export
n_chain.default <- function(x){
    stop("Input must be mcmc.list or data.table generated by mcmc_to_dt.",
         call. = FALSE)
}

#' @export
n_chain.mcmc <- function(x){
    # if is.mcmc(x) 1
    1
}

#' @export
n_chain.mcmc.list <- function(x){
    # if is.mcmc.list length(x)
    length(x)
}

#' @export
n_chain.NULL <- function(x){
    NULL
}

#' @export
n_chain.data.table <- function(x){
    max(x$chain)
}
