#' @importFrom magrittr %>%
NULL

#' @importFrom generics tidy
#' @export
generics::tidy

#' @importFrom generics glance
#' @export
generics::glance

#' @importFrom graphics plot
#' @importFrom stats acf ts.plot

if (getRversion() >= "2.15.1")
  utils::globalVariables(c("."))
globalVariables(
  c(
    "type",
    "deviance.penalised",
    "penalty",
    "deviance",
    "parameter",
    "chain",
    "iteration",
    "deviance_penalised",
    "stan_model",
    "lag",
    "id",
    "value"
  )
)

stop_not_right_for_mmcc <- function() {
  class_list <- c("mcmc",
                  "mcmc.list",
                  "jags",
                  "stanfit",
                  "data.table")

  mmcc_classes <- glue::glue_collapse(class_list,
                                      sep = ", ",
                                      last = " or ")

  message <-
    glue::glue("Input must be {mmcc_classes} generated by mcmc_to_dt.")

  stop(message,
       call. = FALSE)

}
